#!/bin/zsh
if type nvim> /dev/null 2>&1; then
  alias vi=nvim
  alias vim=nvim
  export EDITOR=nvim
fi;
export LESS=FRX
ZGEN_RESET_ON_CHANGE=(${HOME}/.zshrc ${HOME}/.zgen-local-plugins ${HOME}/.zshrc.d/*)

# fpath=(/usr/local/share/zsh-completions $fpath)
# chmod go-w '/usr/local/share'
# unset QUICKSTART_KIT_REFRESH_IN_DAYS
